### PR TITLE
Update tensorflow to v1.8.0

### LINKED ISSUE #88: no such package '@llvm
for shared library

cd tensorflow_cc
mkdir build && cd build
cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..
make && sudo make install

ERROR: /model_pose/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/compiler/xla/client/BUILD:95:1: no such package '@llvm//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/llvm-mirror/llvm/archive/195a164675af86f390f9816e53291013d1b551d7.tar.gz, https://github.com/llvm-mirror/llvm/archive/195a164675af86f390f9816e53291013d1b551d7.tar.gz] to /root/.cache/bazel/_bazel_root/51487c90485c978579d94d2832eb1b9e/external/llvm/195a164675af86f390f9816e53291013d1b551d7.tar.gz: Premature EOF and referenced by '//tensorflow/compiler/xla/client:local_client'
ERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: Loading failed
INFO: Elapsed time: 1065.623s
FAILED: Build did NOT complete successfully (84 packages loaded)
CMakeFiles/tensorflow_shared.dir/build.make:106: recipe for target 'tensorflow-stamp/tensorflow_shared-configure' failed
make[2]: *** [tensorflow-stamp/tensorflow_shared-configure] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tensorflow_shared.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow_shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

@FloopCZ

### LINKED ISSUE #91: Unable to build 1.8.0
Hi,
i'm trying to build tensorflow using 1.8.0 branch with CUDA support.
This is the output i get:
``` /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/tuple: In instantiation of 'static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<int, int, int>&&; bool <anonymous> = true; _Elements = {int, int, int}]':
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/tuple:686:422:   required by substitution of 'template<class ... _UElements, class _Dummy, typename std::enable_if<((std::_TC<(1ul == sizeof... (_UElements)), int, int, int>::_MoveConstructibleTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), int, int, int>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1ul == 1)), int, int, int>::_NonNestedTuple<tuple<_Elements ...>&&>()), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(std::tuple<_Args1 ...>&&) [with _UElements = {int, int, int}; _Dummy = void; typename std::enable_if<((std::_TC<(1ul == sizeof... (_UElements)), int, int, int>::_MoveConstructibleTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), int, int, int>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && std::_TC<(std::is_same<_Dummy, void>::value && (1ul == 1)), int, int, int>::_NonNestedTuple<tuple<_Elements ...>&&>()), bool>::type <anonymous> = <missing>]'
./tensorflow/stream_executor/dnn.h:891:91:   required from here
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/tuple:495:244: error: wrong number of template arguments (4, should be 2)
       return  __and_<__not_<is_same<tuple<_Elements...>,
                                                                                                                                                                                                                                                    ^    
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/type_traits:1558:8: note: provided for 'template<class _From, class _To> struct std::is_convertible'
     struct is_convertible
        ^~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.1/include/c++/tuple:502:1: error: body of constexpr function 'static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<int, int, int>&&; bool <anonymous> = true; _Elements = {int, int, int}]' not a return-statement
     }
 ^
ERROR: /home/marco/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/core/kernels/BUILD:3423:1: output 'tensorflow/core/kernels/_objs/bincount_op_gpu/tensorflow/core/kernels/bincount_op_gpu.cu.pic.o' was not created
ERROR: /home/marco/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/core/kernels/BUILD:3423:1: not all outputs were created or valid
Target //tensorflow:libtensorflow_cc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2036.543s, Critical Path: 137.96s
INFO: 3557 processes, local.
FAILED: Build did NOT complete successfully
make[2]: *** [CMakeFiles/tensorflow_shared.dir/build.make:111: tensorflow-stamp/tensorflow_shared-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/tensorflow_shared.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I'm using Arch Linux with gcc6 if it matter

### LINKED ISSUE #97: Code crashes before reaching main function
Hi,
I have tried to build tensorflow_cc on a new system (I've already got it on two), These are the last lines of the "make" command:

`Target //tensorflow:libtensorflow_cc.so up-to-date:
  bazel-bin/tensorflow/libtensorflow_cc.so
INFO: Elapsed time: 6615.420s, Critical Path: 914.46s
INFO: Build completed successfully, 5743 total actions
find: ‘./bazel-tensorflow/external/cub_archive/tune’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/.settings’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/.cproject’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/LICENSE.TXT’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/eclipse code style profile.xml’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/test’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/WORKSPACE’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/common.mk’: No such file or directory
find: ‘./bazel-tensorflow/external/cub_archive/cub’: No such file or directory
find: ‘./bazel-tensorflow/external/com_google_absl’: No such file or directory
find: ‘./bazel-tensorflow/external/png_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/local_jdk’: No such file or directory
find: ‘./bazel-tensorflow/external/eigen_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/snappy’: No such file or directory
find: ‘./bazel-tensorflow/external/jemalloc’: No such file or directory
find: ‘./bazel-tensorflow/external/jpeg’: No such file or directory
find: ‘./bazel-tensorflow/external/farmhash_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/local_config_git’: No such file or directory
find: ‘./bazel-tensorflow/external/local_config_sycl’: No such file or directory
find: ‘./bazel-tensorflow/external/bazel_tools’: No such file or directory
find: ‘./bazel-tensorflow/external/gemmlowp’: No such file or directory
find: ‘./bazel-tensorflow/external/llvm’: No such file or directory
find: ‘./bazel-tensorflow/external/nasm’: No such file or directory
find: ‘./bazel-tensorflow/external/com_googlesource_code_re2’: No such file or directory
find: ‘./bazel-tensorflow/external/jsoncpp_git’: No such file or directory
find: ‘./bazel-tensorflow/external/nsync’: No such file or directory
find: ‘./bazel-tensorflow/external/gif_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/org_tensorflow’: No such file or directory
find: ‘./bazel-tensorflow/external/lmdb’: No such file or directory
find: ‘./bazel-tensorflow/external/zlib_archive’: No such file or directory
find: ‘./bazel-tensorflow/external/local_config_cuda’: No such file or directory
find: ‘./bazel-tensorflow/external/org_sqlite’: No such file or directory
find: ‘./bazel-tensorflow/external/fft2d’: No such file or directory
find: ‘./bazel-tensorflow/external/protobuf_archive’: No such file or directory
find: ‘./bazel-tensorflow/bazel-out’: No such file or directory
find: ‘./bazel-tensorflow/tensorflow’: No such file or directory
find: ‘./bazel-tensorflow/third_party’: No such file or directory
[ 87%] No build step for 'tensorflow_shared'
[ 93%] No install step for 'tensorflow_shared'
[100%] Completed 'tensorflow_shared'
[100%] Built target tensorflow_shared`

I have no idea about the lines like "find: ‘./bazel-tensorflow/third_party’: No such file or directory" but anyway I tried to build a cpp code with it (the one that I'm using on other systems without a problem), It builds all right but the code crashes before it even reaches the main which makes me think that the problem is with the tensorflow fuctions and libraries being linked.

I would appreciate any help. Thank you.

### PR DESCRIPTION
**Pull request by FloopCZ**
Closes #91 
Closes #88 
Closes #97

### CODE REVIEW

**Comment by achalshah20** [comment]
https://github.com/tensorflow/tensorflow/issues/18980

**Comment by FloopCZ** [comment]
@achalshah20 The CI is passing though, is it just a Debian problem?

**Comment by achalshah20** [comment]
@FloopCZ So If I build on 4 days old commit, it works. But yesterday I tried to pull and build, in that case it failed. So many other people are also facing the same issue. Not sure the cause yet!

**Comment by FloopCZ** [comment]
The issues have been addressed, tests are green, Docker images have been updated. Enjoy.

**Pull request merged**
