### PR TITLE
Add support for matching Protobuf install

### PR DESCRIPTION
**Pull request by FloopCZ**
Hi @xiandong79, feel free to try this if it helps.
`cmake -DINSTALL_PROTOBUF=ON ..`

Relates to #219

### CODE REVIEW

**Comment by xiandong79** [comment]
As I just touch tensorflow cpp, not sure how to resolve this error.

```
ubuntu@ip-172-31-8-224:~/tensorflow_cc/tensorflow_cc/build$ cmake -DSYSTEM_PROTOBUF=ON ..
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindProtobuf.cmake:543 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:58 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/tensorflow_cc/tensorflow_cc/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/tensorflow_cc/tensorflow_cc/build/CMakeFiles/CMakeError.log".
```

**Comment by FloopCZ** [comment]
And do you have Protobuf installed in your system?

**Comment by xiandong79** [comment]
@FloopCZ 
```
ubuntu@ip-172-31-8-224:~$ protoc --version
libprotoc 3.11.4
```

maybe I just do some wrong operations that I donot realize. sorry to waste your time.

**Comment by xiandong79** [comment]
Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)

maybe the config file is wrong?

**Comment by FloopCZ** [comment]
That is why I don't really like the idea of linking system protobuf. But this error is already when cmake calls `find_package`, which is weird. Can you `ls -la /usr/lib/libprotobuf*` please?

**Comment by cweigel** [comment]
Hi,

just my two cents / experiences about that.

1. The system protobuf installation of @xiandong79 may only contain the runtime files - not the development files or might be in the wrong version

2. We've also ran into the issue with missing protobuf - the thing is that protobuf is very picky to match its exact version therefore we've compile protobuf (the static protobuf.a) in exactly the version that was used in the respective tensorflow version and linked it to our main program. I also tried to compile it form the source code version that is downloaded by bazel during the tensorflow build but that is somehow a "special" reduced version.

3. A better approach to resolve this within this project would probably be to 1. find out which version is used and 2. add this version as another external project to this repo.

**Comment by FloopCZ** [comment]
@xiandong79 @cweigel According to your suggestions, there is an option `-DINSTALL_PROTOBUF=ON` which installs a Protobuf version compatible with the current TensorFlow version. You still have to use `find_package(Protobuf)` and link the Protobuf library to your executable, but by default, it should be installed in `/usr/local` and CMake should prefer it to your system Protobuf.

**Pull request merged**
